# Generated by Django 5.0 on 2023-12-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_rename_mname_moviedetails_moname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='payment',
        ),
    ]
